INSERT INTO t_user (name, email, password) VALUES ('Aakash Chopra', 'akchopra12@gmail.com', 'akchopra@1223');
INSERT INTO t_user (name, email, password) VALUES ('Rohan Mehra', 'rohan.mehra89@example.com', 'rohan@123');
INSERT INTO t_user (name, email, password) VALUES ('Neha Sinha', 'neha.sinha22@example.com', 'neha@123');
INSERT INTO t_user (name, email, password) VALUES ('Amit Tiwari', 'amit.tiwari78@example.com', 'amit@456');
INSERT INTO t_user (name, email, password) VALUES ('Priya Deshmukh', 'priya.desh56@example.com', 'priya@789');
INSERT INTO t_user (name, email, password) VALUES ('Kunal Sharma', 'kunal.sharma55@example.com', 'kunal@abc');
INSERT INTO t_user (name, email, password) VALUES ('Sneha Kapoor', 'sneha.kapoor33@example.com', 'sneha@xyz');
INSERT INTO t_user (name, email, password) VALUES ('Nikhil Rao', 'nikhil.rao88@example.com', 'nikhil@2023');
INSERT INTO t_user (name, email, password) VALUES ('Isha Bansal', 'isha.bansal91@example.com', 'isha@pass');
INSERT INTO t_user (name, email, password) VALUES ('Aditya Khurana', 'aditya.khurana64@example.com', 'aditya@321');
INSERT INTO t_user (name, email, password) VALUES ('Tanya Verma', 'tanya.verma12@example.com', 'tanya@t12');
INSERT INTO t_user (name, email, password) VALUES ('Manav Saxena', 'manav.saxena70@example.com', 'manav@456');
INSERT INTO t_user (name, email, password) VALUES ('Divya Rathi', 'divya.rathi23@example.com', 'divya@r23');
INSERT INTO t_user (name, email, password) VALUES ('Rajeev Nair', 'rajeev.nair11@example.com', 'rajeev@nai1');
INSERT INTO t_user (name, email, password) VALUES ('Meera Joshi', 'meera.joshi82@example.com', 'meera@jos');
INSERT INTO t_user (name, email, password) VALUES ('Harsh Vardhan', 'harsh.vardhan34@example.com', 'harsh@vardhan');
INSERT INTO t_user (name, email, password) VALUES ('Pooja Thakur', 'pooja.thakur99@example.com', 'pooja@1234');
INSERT INTO t_user (name, email, password) VALUES ('Arjun Dey', 'arjun.dey75@example.com', 'arjun@pass');
INSERT INTO t_user (name, email, password) VALUES ('Kritika Yadav', 'kritika.yadav24@example.com', 'kritika@y24');
INSERT INTO t_user (name, email, password) VALUES ('Siddharth Dubey', 'siddharth.dubey16@example.com', 'sidd@dub');
INSERT INTO t_user (name, email, password) VALUES ('Ananya Bhatia', 'ananya.bhatia60@example.com', 'ananya@pass');
INSERT INTO t_user (name, email, password) VALUES ('Yash Patel', 'yash.patel08@example.com', 'yash@123');
INSERT INTO t_user (name, email, password) VALUES ('Ritika Malhotra', 'ritika.mal90@example.com', 'ritika@pass');
INSERT INTO t_user (name, email, password) VALUES ('Vikram Sethi', 'vikram.sethi14@example.com', 'vikram@st14');
INSERT INTO t_user (name, email, password) VALUES ('Bhavna Chawla', 'bhavna.chawla38@example.com', 'bhavna@chawla');
INSERT INTO t_user (name, email, password) VALUES ('Aarav Kulkarni', 'aarav.kulkarni51@example.com', 'aarav@kul51');

INSERT INTO user_roles(user_id, roles) VALUES (1, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (2, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (2, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (3, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (3, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (4, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (4, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (5, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (5, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (6, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (6, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (7, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (7, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (8, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (8, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (9, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (9, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (10, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (10, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (11, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (11, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (12, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (12, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (13, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (13, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (14, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (14, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (15, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (15, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (16, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (16, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (17, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (17, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (18, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (18, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (19, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (19, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (20, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (20, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (21, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (21, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (22, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (22, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (23, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (23, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (24, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (24, 'DRIVER');
INSERT INTO user_roles(user_id, roles) VALUES (25, 'RIDER');
INSERT INTO user_roles(user_id, roles) VALUES (25, 'DRIVER');

INSERT INTO t_rider (user_id, rating) VALUES (1, 4.9);

INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (1, 4.8, true, ST_GeomFromText('POINT(73.7997 18.6298)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (2, 4.2, true, ST_GeomFromText('POINT(73.7854 18.6201)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (3, 3.9, true, ST_GeomFromText('POINT(73.8150 18.6355)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (4, 5.0, true, ST_GeomFromText('POINT(73.8011 18.6543)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (5, 4.5, true, ST_GeomFromText('POINT(73.7743 18.6182)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (6, 4.0, true, ST_GeomFromText('POINT(73.8391 18.6109)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (7, 3.7, true, ST_GeomFromText('POINT(73.7538 18.6401)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (8, 4.9, true, ST_GeomFromText('POINT(73.7200 18.6560)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (9, 3.5, true, ST_GeomFromText('POINT(73.8123 18.5987)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (10, 4.3, true, ST_GeomFromText('POINT(73.8305 18.6689)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (11, 3.8, true, ST_GeomFromText('POINT(73.7680 18.5872)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (12, 4.1, true, ST_GeomFromText('POINT(73.8430 18.6485)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (13, 3.3, true, ST_GeomFromText('POINT(73.7570 18.6702)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (14, 4.6, true, ST_GeomFromText('POINT(73.7970 18.6890)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (15, 3.6, true, ST_GeomFromText('POINT(73.7745 18.5825)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (16, 4.4, true, ST_GeomFromText('POINT(73.8208 18.6952)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (17, 3.4, true, ST_GeomFromText('POINT(73.8312 18.5748)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (18, 5.0, true, ST_GeomFromText('POINT(73.7550 18.6979)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (19, 4.7, true, ST_GeomFromText('POINT(73.8601 18.6175)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (20, 3.2, true, ST_GeomFromText('POINT(73.7425 18.6783)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (21, 4.3, true, ST_GeomFromText('POINT(73.8269 18.6620)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (22, 4.0, true, ST_GeomFromText('POINT(73.7505 18.6020)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (23, 3.1, true, ST_GeomFromText('POINT(73.7912 18.6850)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (24, 3.8, true, ST_GeomFromText('POINT(73.8450 18.6005)', 4326));
INSERT INTO t_driver (user_id, rating, available, current_location) VALUES (25, 4.5, true, ST_GeomFromText('POINT(73.7653 18.6732)', 4326));

INSERT INTO t_wallet (user_id, balance) VALUES (1, 100);
INSERT INTO t_wallet (user_id, balance) VALUES (2, 500);
